function controlleur = generateContolleur(drone)

M_k = pinv(drone.Mb);
%% initialize controlleur structure
controlleur = struct('k1',1.0, ...
                     'kc',5, ...
                     'kv',1.0, ...
                     'ku',600.0, ...
                     'kgamma',1.0, ... 
                     'M_k',M_k, ...
                     'kd',60, ...
                     'k_s',0.01 ...
                     );
end